### ISSUE TITLE
Step 8. Install the AstroPlant Kit software needs root

### ISSUE THREAD

**Issue by davidhoness** [AstroPlant/sensor-test-scripts#3]
```
$ python3 -m pip install git+https://github.com/AstroPlant/astroplant-peripheral-device-library@1.0.0b1
$ python3 -m pip install git+https://github.com/AstroPlant/astroplant-kit@1.0.0b3
```
Tested on Raspbian buster  4.19.75-v7+ these commands will install the files into `/home/pi/.local` unless elevated permissions are given. Change setup steps to include sudo here.

**Comment by SidneyNiccolson** [comment]
Please move this issue under the relevant repository, that is https://github.com/AstroPlant/astroplant-kit.

**Comment by davidhoness** [comment]
You just need to put `sudo` into the instructions page for these commands I think - you think the library needs to change?

**Comment by tomcur** [comment]
Thanks for the report. I don't think `sudo` is necessary. The software is intended to be run without elevated privileges, so it makes sense for the Python packages to be installed only for the unprivileged user.

**Comment by davidhoness** [comment]
It might work as is if you export `/home/pi/.local/bin` into the PATH environment variable. I haven't tested this though.
